# Generated by Django 4.2.17 on 2024-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
