# Generated by Django 4.2.17 on 2024-12-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_category_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_img',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product',
        ),
    ]
