# Generated by Django 4.2.17 on 2024-12-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_work_remove_category_category_remove_product_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='name',
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to='shop/catalog/static/catalog/works/'),
        ),
    ]
